[build-system]
requires = [
	"scikit-build-core",
    "scikit-build-core[pyproject]",
	"cython >= 3.0.8",
]
build-backend = "scikit_build_core.build"

[project]
name = "smtk_draco"
version = "1.0.1"
description = "Python wrapper of Blenders Draco bridging library"
requires-python = ">= 3.8"
authors = [
    {name = "barasimumatik"},
]
maintainers = [
	{name="Simumatik"}
]
readme = "README.md"
keywords = ["draco", "mesh compression", "gltf", "glb"]
license = {text="Apache License Version 2.0 (see LICENSE)"}
classifiers = [
	"Intended Audience :: Developers",
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
]

[project.urls]
Repository = "https://github.com/Simumatik/smtk_draco"
Issues = "https://github.com/Simumatik/smtk_draco/issues"

[tool.scikit-build]
cmake.version = ">=3.18"
cmake.verbose = true
sdist.exclude = [
    "draco/.github", 
    "draco/docs", 
    "draco/javascript",
    "draco/maya", 
    "draco/testdata",
    "draco/third_party", 
    "draco/unity", 
]

[tool.cibuildwheel]
test-command = "python \"{project}/tests/test.py\""
