[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coollog"
version = "0.1.3"
description = "A simple and colorful logger for Python"
readme = "README.md"
license = {text = "MIT"}
authors = [
  { name="Mohammad Reza Hosein Nia", email="id.suzuya@email.com" }
]
keywords = ["logger", "color", "console", "python"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = []

[project.urls]
"Homepage" = "https://github.com/mmd-dll/coollog"
"Bug Tracker" = "https://github.com/mmd-dll/coollog/issues"
