[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "anydbx"
version = "0.1.1"
description = "Agnostic SQLAlchemy helper with engine registry, safe transactions, and pandas I/O."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "Daniel Torres" }]
keywords = ["sqlalchemy", "database", "mysql", "mssql", "duckdb", "pandas"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Topic :: Database",
]

dependencies = [
  "SQLAlchemy>=1.4,<3",
  "pandas>=1.5",
]

[project.optional-dependencies]
mysql = ["pymysql>=1.0"]
mssql = ["pymssql>=2.2"]
duckdb = ["duckdb>=1.0", "duckdb-engine>=0.11"]
postgres = ["psycopg[binary]>=3.1"]

[project.urls]
Homepage = "https://github.com/nargotik/anydbx"

[tool.hatch.build.targets.wheel]
packages = ["src/anydbx"]
