[project]
name = "vinci-lang"
version = "1.0.6"
description = "VINCI is a general purpose programming language that is numbers oriented and retro."
authors = [
    { name = "SeafoodStudios" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.poetry.scripts]
vinci-lang = "vinci_lang.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"