[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "drap"
version = "0.0.3.post11"
description = "Tool for analyzing droplet size and concentration using video and EDF images"
readme = "README.md"
license = {text = "MIT"}
authors = [{ name = "Gabriel Braga Marques Teobaldo, Oleg Prymak, Natalie Wolff,  Matthias Epple, Marco Aurélio Brizzotti Andrade, Cássio Alves and Cristiano Luis Pinto de Oliveira", email = "alves.casssio@gmail.com" }]
requires-python = ">=3.10"

dependencies = [
  "opencv-python-headless>=4.9",  
  "PyQt5>=5.15",
  "numpy",
  "matplotlib",
  "fabio",
  "pillow",
  "reportlab"
]

keywords = ["saxs", "x-ray", "edf", "opencv", "pyqt5", "droplet"]

[project.scripts]
drap = "drap.main:main"
drap-gui = "drap.gui:main_gui" 

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://test.pypi.org/project/DrAP/"
Source = "https://test.pypi.org/project/DrAP/"
