[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-ant-autoapi"
version = "0.1.3"
description = "Auto-generate CRUD API views for Django models."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
  { name = "daxu", email = "xuh@daxu.cc" }
]
dependencies = [
  "Django>=4.0",
  "djangorestframework>=3.14",
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["autoapi*"]   # 只打包 autoapi 目录
exclude = ["core*", "tests*",'templates']   # 排除 core 和测试目录


[project.urls]
Homepage = "https://github.com/buslink/Dango-Ant-Admin"
Documentation = "https://github.com/buslink/Dango-Ant-Admin#readme"
Source = "https://github.com/buslink/Dango-Ant-Admin"
Issues = "https://github.com/buslink/Dango-Ant-Admin/issues"