[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "whis"
version = "0.1.0a4"  # next alpha
description = "A tiny Linux command whisperer that suggests shell commands based on natural language."
readme = "README.md"
license = { file = "LICENSE" , content-type = "text/markdown" }
requires-python = ">=3.10"  # todo add support for <=3.12

authors = [
  { name = "Milan Slesarik", email = "milslesarik@gmail.com" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    "Topic :: Utilities",
]

dependencies = [
  "openai",
  "ollama",
  "pyperclip",  # clipboard management
    "tomli >= 1.2.0; python_version < '3.11'"

]

[project.scripts]
whis = "whis.__main__:main"

[project.urls]
Homepage = "https://github.com/milano-slesarik/whis"
"Bug Tracker" = "https://github.com/milano-slesarik/whis/issues"

[tool.setuptools]
packages = { find = { include = ["whis*"] } }

[tool.setuptools.package-data]
whis = ["config.template.toml", "system_prompt.txt"]

[project.optional-dependencies]
dev = [
  "dotenv",
  "pytest",
  "pytest-cov",
  "black",
  "ruff",
  "pre-commit>=4.3.0,<5"

]

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
addopts = "-q --cov=whis --cov-report=term-missing --cov-report=xml  --cov-fail-under=67"

[tool.coverage.run]
branch = true
source = ["whis"]
omit = [
    "whis/__main__.py",
    "whis/smoke.py",
    "whis/__init__.py"
]

[tool.coverage.report]
skip_empty = true
show_missing = true
