[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "roself"                 # pip install roself
version = "0.2.0"
description = "roself is a Python-based interactive ROS1 Topic Browser that lets you explore, filter, drill down, and monitor topics in a command-line TUI (Text-based User Interface)."
readme = "README.md"
license = {text = "MIT"}
authors = [
  { name="XiaoMing", email="mesakas@icloud.com" }
]
dependencies = [
  "rospy",
  "roslib",
  "rosgraph"
]

[project.urls]
Homepage = "https://github.com/mesakas/roself"

[project.scripts]
roself = "roself.cli:main"
