[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "phicode"
version = "2.6.0"
description = "(φ) Phicode Runtime Engine — Optimized for stability under load (CPython/PyPy Supported)"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name="Jay Baleine", email="jay@banes-lab.com" }
]
requires-python = ">=3.8"
dependencies = [
    "xxhash>=3.0.0",
    "regex>=2025.7.34"
]

[project.optional-dependencies]
utility = ["psutil>=5.8.0"]
rust = []

[project.scripts]
phicode = "phicode_engine.engine:main"
phi = "phicode_engine.engine:main"
phicode-api = "phicode_engine.api.cli:main"
aphi = "phicode_engine.api.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["phicode_engine*"]

[tool.setuptools.package-data]
"phicode_engine.api" = ["*.py"]
"phicode_engine.rust" = ["*.py"]
"phicode_engine.security" = ["*.py"]
"phicode_engine.installers" = ["*.py"]
"phicode_engine.benchsuite" = ["*.φ"]
"phicode_engine.benchsuite.simulation" = ["*.φ"]