[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coraw"
version = "0.1.4"
description = "Simplest cozmo raw data sender"
authors = [{ name="Alan", email="dipdoptrip@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pynput", "inputs", "opencv-python"]
