[build-system]
requires = [
    "scikit-build-core",
    "setuptools_scm[toml]>=6.2"
]
build-backend = "scikit_build_core.build"

[project]
name = "flexaid-py"
dynamic = ["version"]
description = "Python wheels and a wrapper for FlexAID, a tool for docking"
authors = [
    {name = "Thomas DesCÃ´teaux"},
    {name = "Rafael Najmanovich", email = "rafael.najmanovich@umontreal.ca"},
]
classifiers = [
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Natural Language :: English',
]

readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/NRGlab"
Documentation = "https://github.com/NRGlab/flexaid-py/blob/main/README.md"
Repository = "https://github.com/NRGlab/flexaid-py"
Issues = "https://github.com/NRGlab/flexaid-py/issues"

[tool.scikit-build]
wheel.install-dir = "flexaidpy"
wheel.py-api = "py3"
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
cmake.build-type = "Release"

[tool.setuptools.packages.find]
include = ["flexaidpy","flexaidpy.*"]

[tool.setuptools_scm]

[tool.cibuildwheel]
build = "cp39-*"
skip = [
    "*-win32",
    "*-manylinux_i686",
    "*-musllinux*",
]

environment-pass = ["CIBW_BUILD"]