[project]
name = "fast_fig"
version = "0.8.1"
description = "FaSt_Fig is a wrapper for matplotlib with templates."
authors = [
    {name = "Fabian Stutzki", email = "fast@fast-apps.de"}
]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["matplotlib", "figure"]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.26.0",
    "matplotlib>=3.6.0",
    "pandas>=2.1.0",
    "pyyaml>=6.0.2",
    "logging>=0.4.0",
    "pathlib>=1.0.0",
    "typing-extensions>=4.0.0",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203",  # Ignore 'incorrect-blank-line-before-class' in favor of D211
    "D213",  # Ignore 'multi-line-summary-second-line' in favor of D212
    "COM812",  # Ignore to avoid conflicts with the formatter
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "S101",  # Ignore assert statements in tests
    "PLR2004",  # Ignore magic numbers in tests
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-cov>=6.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
