[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "khutils"
version = "1.0.2"
license = { text = "MIT" }
dependencies = []
description = "Utilities for converting numbers, dates, and text to/from Khmer"
authors = [{ name="Chorn Penghong", email="chorn.penghong168@gmail.com" }]
readme = "README.md"
keywords = ["khmer", "khmer number", "khmer date", "khmer text"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]