[project]
name = "ya-market-api"
version = "2.0.0"
description = "Yandex.Market seller API client"
readme = "README.md"
authors = [
    { name = "Kirill_Lekhov", email = "kirill.lekhov@mail.ru" }
]
requires-python = ">=3.8.1"
dependencies = [
    "arrow>=1.3.0",
    "pydantic>=2.10.6",
]
license = { file = "LICENSE" }

[project.optional-dependencies]
all = [
    "aiohttp>=3.10.11",
    "requests>=2.32.4",
]
sync = [
    "requests>=2.32.4",
]
async = [
    "aiohttp>=3.10.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "aiohttp>=3.10.11",
    "flake8>=7.1.2",
    "flake8-zale>=0.2.1",
    "ipython>=8.12.3",
    "pip-audit-extra>=0.1.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=5.0.0",
    "requests>=2.32.4",
]
