[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "competencia_mexico"
version = "0.1.5"
description = "Herramientas para análisis de competencia económica, precios, visualización y RAG (FAISS + DeepSeek)"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Iván Paredes Reséndiz", email="ivanresendiz25@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "pandas>=1.3",
    "numpy>=1.21",
    "matplotlib>=3.5",
    "requests>=2.28",
    "langchain-community>=0.2.0",
    "sentence-transformers>=2.5.0",
    "faiss-cpu>=1.7.4",
    'importlib-resources>=5.12; python_version < "3.9"'
]

[project.optional-dependencies]
dev = ["pytest", "black", "ruff", "twine", "build"]

[tool.setuptools]
packages = ["competencia_mexico"]
include-package-data = true

[tool.setuptools.package-data]
competencia_mexico = [
    "data/*.csv",
    "data/faiss_index/*"
]







