[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deezspot-spotizerr"
version = "3.1.2"
description = "Downloads songs, albums or playlists from deezer and spotify (clone from deezloader)"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GNU Affero General Public License v3"}
authors = [
    {name = "jakiepari", email = "farihmuhammad75@gmail.com"}
]

dependencies = [
    "mutagen==1.47.0",
    "pycryptodome==3.23.0",
    "requests==2.32.3",
    "tqdm==4.67.1",
    "fastapi==0.116.1",
    "uvicorn[standard]==0.35.0",
    "librespot-spotizerr==0.3.0",
    "rapidfuzz==3.13.0",
    "spotipy==2.25.1"
]

[project.urls]
Homepage = "https://github.com/Xoconoch/deezspot-spotizerr"
Repository = "https://github.com/Xoconoch/deezspot-spotizerr.git"
Documentation = "https://github.com/Xoconoch/deezspot-spotizerr/blob/main/README.md"

[tool.setuptools.packages.find]
include = ["deezspot", "deezspot.*"]
