[project]
name = "funclp"
version = "0.1.0"
description = "A library for defining mathematical functions and fits."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "corelp",
    "pytest>=8.4.1",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
    "toml>=0.10.2",
]
[[project.authors]]
name = "LancelotPincet"
email = "40608570+LancelotPincet@users.noreply.github.com"

[build-system]
requires = [ "uv_build>=0.8.8,<0.9.0",]
build-backend = "uv_build"

["tool.uv"]
required-environments = [ "sys_platform == 'linux' and platform_machine == 'x86_64'", "sys_platform == 'win32' and (platform_machine == 'AMD64' or platform_machine == 'x86_64')",]

[tool.uv.sources]
corelp = { workspace = true }
