[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rejgoo"
version = "0.0.5"
description = "Python package that solves mathematical equations"
readme = "README.MD"
requires-python = ">= 3.10"
authors = [
  {name = "Mahdi Hajebi", email = "merto071@yahoo.com"}
]
maintainers = [
  {name = "Mahdi Hajebi", email = "merto071@yahoo.com"}
]
classifiers = [

]
license = {text = "MIT license"}
dependencies = [
    "numpy (>=2.0.0,<3.0.0)",
    "CoolProp (>=6.7.0,<7.0.0)"

]

[project.optional-dependencies]
dev = [
    "coverage",  # testing
    "pytest",  # testing
]

[project.urls]

bugs = "https://github.com/mertomax/rejgoo/issues"
changelog = "https://github.com/mertomax/rejgoo/blob/master/changelog.md"
homepage = "https://github.com/mertomax/rejgoo"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]




# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"

