[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Apimatic"
version = "0.1.6"
description = "Universal API documentation generator"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Matrixxboy", email = "matrix.utsav.lankapati@gmail.com"},
]
dependencies = [
    "pyyaml",
    "openai",
    "google-generativeai",
    "groq",
]

[project.scripts]
Apimatic = "Apimatic.cli:main"
