[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'


[project]
name = 'sqlvault'
authors = [
    { name = 'Peter Mirzoian', email = 'fragarie.dev@yandex.com' },
]
description = 'Simple SQL-based key/value store'
readme = 'README.md'
license = {file = 'LICENSE'}
classifiers = [
    'Programming Language :: Python :: 3',
]
requires-python = '>=3.12'
dependencies = [
    'sqlalchemy>=2.0.0',
]
dynamic = ['version']

[tool.setuptools.dynamic]
version = {attr = 'sqlvault.VERSION'}

[tool.setuptools.packages.find]


[tool.pytest.ini_options]
pythonpath = ['.']

[tool.flake8]
exclude = ['.venv', '.git', 'dist', '*egg-info']
per-file-ignores = [
    '__init__.py: WPS410, WPS412',
    'base.py: WPS110, WPS214',
    'vault.py: WPS110, WPS214',
    'tests/*: WPS110, WPS202, WPS226, WPS432'
]

[tool.ruff.format]
quote-style = 'single'
