[project]
name = "tabaml"
version = "0.2.1"
description = "TabAML is a framework for tabular data classification models"
readme = "README.md"
authors = [
  { name="xiaoql", email="xiaoql@hollycrm.com" },
]
requires-python = ">=3.9"
dependencies = [
    "fastparquet>=2024.11.0",
    "numpy",
    "pandas",
    "torch",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Qiliang/tabaml"
Issues = "https://github.com/Qiliang/tabaml/issues"

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
