[project]
name = "testmark-pytest"
version = "0.0.1"
description = "Write language-agnostic unit tests in Markdown. Run them in pytest."
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Matt Holden" }]
license = { text = "MIT" }

[project.urls]
Repository = "https://github.com/holdenmatt/testmark"

[tool.uv]
dev-dependencies = ["pytest>=8.0.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.pytest.ini_options]
python_functions = "test_*"