[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "temfield"
version = "0.1.0"
authors = [
    {name = "Hans Georg Krauthäuser", email = "hgk@ieee.org"}
]
maintainers = [
  {name = "Hans Georg Krauthäuser", email = "hgk@ieee.org"}
]
description = "Radiated EMC susceptibility measurements in (G)TEM wavegides using mpylab"
readme = "README.md"
requires-python = ">=3.8"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["EMC", "measurements", "laboratory"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Topic :: Scientific/Engineering",
    # Specify the Python versions you support here.
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]
dependencies = [
    "matplotlib>=3.7.5",
    "mpylab>=0.9.1",
    "numpy>=1.24.4",
    "pyside6>=6.6.3.1",
]

[project.scripts]
temfield = "temfield.TEMField:main"

[project.urls]
Repository = "https://github.com/hgkdd/TEMField"

