# pyproject.toml

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kececinumbers"
version = "0.6.1"

# Diğer proje bilgileri (isteğe bağlı ama tavsiye edilir)
authors = [
    { name="Mehmet Keçeci", email="mkececi@yaani.com" },
]
description = "Keçeci Numbers: An Exploration of a Dynamic Sequence Across Diverse Number Sets"
readme = "README.md"
requires-python = ">=3.10"
license = { file="LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Visualization",
]

# Ana bağımlılıklarınız
dependencies = [
    "numpy",
    "matplotlib",
    "numpy-quaternion",
    "sympy",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
    "numpy",
    "matplotlib",
    "numpy-quaternion",
    "sympy",
]

[tool.setuptools.packages.find]
where = ["."]

[project.urls]
Homepage = "https://github.com/WhiteSymmetry/kececinumbers"
Repository = "https://github.com/WhiteSymmetry/kececinumbers"
