[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iflow-mcp_imdb-mcp-server"
version = "1.0.2"
description = "A Python server implementing Model Context Protocol (MCP) for movie and TV show information using the IMDb API service"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "uzaysozen", email = "uzaysozen@example.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.10"
dependencies = [
    "requests",
    "mcp[cli]<=1.10.1"
]

[project.scripts]
imdb-mcp-server = "imdb_server:main"

[tool.setuptools]
py-modules = ["imdb_server"]