[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "questions-cli"
version = "0.1.0"
description = "CLI for processing search queries for the app"
readme = "README.md"
authors = [{ name = "InshaManowar" }]
requires-python = ">=3.9"
license = { file = "LICENSE" }
keywords = ["cli", "questions", "search", "queries"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "typer>=0.9,<1.0",
  "pydantic>=2.4",
  "pandas>=2.0",
  "pymongo>=4.6",
  "loguru>=0.7",
  "orjson>=3.9",
  "python-dotenv>=1.0",
  "tqdm>=4.66",
  "httpx>=0.27",
  "tenacity>=8.2",
  "pyyaml>=6.0",
]

[project.scripts]
questions-cli = "questions_cli_app.cli:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["questions_cli_app*"]


