[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maleo-metadata"  # PyPI package name
version = "0.2.56"
description = "MaleoMetadata service package"
authors = [
    { name = "Agra Bima Yuda", email = "agra@nexmedis.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "maleo-soma>=0.2.1"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["maleo.metadata*"]

[tool.setuptools.package-data]
"maleo.metadata" = ["*.json", "*.yaml"]