[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyodys"
version = "0.0.2"
dependencies = [
    "numpy",
    "scipy"
]
description = "This is a robust and flexible Python package for solving ordinary differential equations (ODEs). The solver is built to handle both explicit and implicit Runge–Kutta methods using a powerful Butcher tableau approach, and it includes a numerical Jacobian for convenience."
authors = [
    { name = "Ismaël Tchinda Ngueyong", email = "itchindan@gmail.com" }
]