[project]
name = "mcp-server-stat"
version = "0.1.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.11.3",
]

[project.scripts]
mcp-server-stat = "mcp_server_stat:main"