[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "git-tag-deploy"
version = "0.2.1"
description = "Dev tool to deploy git-tagged versions of a FastAPI app"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Tenbatsu24", email = "puruvaish24@outlook.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Utilities"
]
keywords = ["fastapi", "deployment", "git", "automation", "cli"]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]

dependencies = [
    "pyyaml",
    "fastapi",
    "uvicorn"
]

[project.scripts]
# CLI entry point
git-tag-deploy = "git_tag_deploy.cli:main"

[project.urls]
"Homepage" = "https://github.com/Tenbatsu24/git-tag-deployment"
"Documentation" = "https://github.com/Tenbatsu24/git-tag-deployment#readme"

[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
