[build-system]
# 3.4 이상이어야 pip install -e 가 가능하다
requires = ["flit_core >=3.7"]
build-backend = "flit_core.buildapi"

[project]
name = "shared_lib_ds"
version = "1.5.2"
description = "Demiansoft template(shared_lib)"
readme = "README.md"
requires-python = ">=3.6"
#license = {text = "MIT"}
#authors = [
#    {name = "Hyungjin Kim", email = "hj3415@gmail.com"}
#]
#keywords = ["keyword1", "keyword2", "keyword3"]
#classifiers = [
#    "Programming Language :: Python :: 3",
#    "License :: OSI Approved :: MIT License",
#    "Operating System :: OS Independent"
#]
dependencies = [
    "Django>=4.2.11",
    "Pillow>=10.4.0", # 모델에서 이미지 저장 위해
    "django-easymde>=1.0.4", # 블로그 마크다운에디터
    "django-hitcount>=1.3.5", # 블로그 히트카운터
    "django-taggit>=6.1.0", # 블로그 태그 관리
    "django-jazzmin>=3.0.1", # 관리자 페이지 UI
    "django-markdownx>=4.0.7",
    "utils_hj3415>=3.2.0", # 메일보내기
]

[tool.flit.module]
name = "shared_lib"  # 배포 패키지 이름과 모듈 이름이 다른 경우. 3.7이상에서 사용
