[project]
name = "meta-paper"
version = "0.4.1"
description = "Python client for fetching scientific paper metadata from multiple sources"
authors = [
    {name = "Andrei Olar", email = "andrei.olar@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
packages = ["meta_paper"]
requires-python = ">=3.11"
dependencies = [
    "httpx (>=0.28.1,<0.29.0)",
    "tenacity (>=9.0.0,<10.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
black = "^24.10.0"
ruff = "^0.9.3"
mypy = "^1.14.1"
pytest-asyncio = "^0.25.2"

[tool.pytest.ini_options]
addopts = "--strict-markers -ra"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]