[tool.poetry]
name = "outflow"
version = "0.9.1"
description = "Outflow is a framework that helps you create and execute sequential, parallel as well as distributed task workflows."
authors = ["Gregoire Duvauchelle <gregoire.duvauchelle@lam.fr>", "Sonny LION <sonny.lion@obspm.fr>", "ROC Team <roc.support@sympa.obspm.fr>"]
readme = "README.md"
license = "CECILL-2.1"
homepage = "https://outflow.dev"
repository = "https://gitlab.com/outflow-project/outflow"
keywords = ["outflow", "pipeline", "distributed", "parallel", "workflow", "data science", "slurm"]
classifiers = [
    "Environment :: Console",
    "Development Status :: 4 - Beta",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3 :: Only"
]

[tool.poetry.urls]
"Documentation" = "https://docs.outflow.dev"
"Tracker" = "https://gitlab.com/outflow-project/outflow/-/issues"

[tool.poetry.dependencies]
python = ">=3.9,<4"
importlib-metadata = {version = "~4.8.1", python = "<3.8"}
networkx = ">2.6"
typeguard = "~4.4.4"
cloudpickle = "^3.1.1"
declic = ">=1.0.2"
toml = "^0.10.1"
sqlalchemy = "<2"
alembic = "~1.16"
psycopg2-binary = "~2.9.1"
jinja2 = "^3.1.2"
simple-slurm = "~0.2.2"
typing-extensions = ">3.10.0.2"
black = "~25.1.0"
pytest = {version = "^8.4", optional = true}
pytest-timeout = {version = "^2.4", optional = true}
pytest-cov = {version = "^6.2", optional = true}
pytest-postgresql = {version = "^7.0", optional = true}
pyyaml = "^6"
pyyaml-include = "^2.0"
rich = ">10.13.0"
ipython = {version = "^8.4.0", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.4"
pytest-cov = "^6.2"
pytest-timeout = "^2.4"
pre-commit = "^4.3"
pytest-postgresql = "^7.0"

[tool.poetry.extras]
tests = ["pytest", "pytest-cov", "pytest-timeout", "pytest-postgresql", "ipython"]
ipython = ["ipython"]


[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=1.1.8", "setuptools"]
build-backend = "poetry.core.masonry.api"
