#*****************************************************************#
# (C) Copyright IBM Corporation 2020.                             #
#                                                                 #
# The source code for this program is not published or otherwise  #
# divested of its trade secrets, irrespective of what has been    #
# deposited with the U.S. Copyright Office.                       #
#*****************************************************************#

# TODO: We need a model repo for watson_ts that's not watson_nlp's!!
artifactory_base_path: https://na.artifactory.swg-devops.com/artifactory/api/storage/wcp-ai-foundation-team-watson-ts-generic-local/
watson_ts_version: 0.0.1
