#*****************************************************************#
# (C) Copyright IBM Corporation 2020.                             #
#                                                                 #
# The source code for this program is not published or otherwise  #
# divested of its trade secrets, irrespective of what has been    #
# deposited with the U.S. Copyright Office.                       #
#*****************************************************************#
artifactory_base_path: https://na.artifactory.swg-devops.com/artifactory/api/storage/wcp-nlu-team-one-nlp-models-generic-local/
enable_error_checks: true
max_exception_log_messages: 4
load_path: null
beta:
  catalog:
    repos:
      - default: false
        nickname: stock
        path: ~/.watson_nlp/repos/stock-beta
        readonly: true
        remote:
          path: wcp-nlu-team-one-nlp-models-generic-local/.repos/stock-beta
          type: artifactory
          url: https://na.artifactory.swg-devops.com
      - default: true
        nickname: custom
        path: ~/.watson_nlp/repos/custom-beta
        readonly: false
        remote:
          type: local
