[project]
name = "odoo_py"
version = "0.0.17"
authors = [
  { name="Rafael Galleani", email="rafegal@gmail.com" },
]
description = "Package to abstract the Odoo API"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "environs>=9.5.0"
]

[project.urls]
Homepage = "https://github.com/IT-NOSSA-FARMACIA/odoo-py"
Issues = "https://github.com/IT-NOSSA-FARMACIA/odoo-py"