[build-system]
requires = ["setuptools>=45", "wheel", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "chATLAS_Chains"
version = "0.1.5"
description = "A modular Python package for implementing Retrieval Augmented Generation chains for the chATLAS project."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "Apache-2.0"}
authors = [
    {name = "Joe Egan", email = "joseph.caimin.egan@cern.ch"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "chatlas-embed>=0.1.19",
    "langchain~=0.3.3",
    "langchain_core",
    "langchain_openai",
    "langgraph",
    "sentence-transformers>=3.0.0",
    "tiktoken",
    "pinecone",
    "torch==2.2.1",
    "chatlas-embed",
    "psycopg2-binary>=2.9.10",
]

[project.urls]
Homepage = "https://gitlab.cern.ch/atlasml/chatlas/chatlas-packages/"

[dependency-groups]
dev = [
    "pytest>=8.3.5"
]

[tool.setuptools.packages.find]

[tool.ty]
environment.extra-paths = ["../chATLAS_Embed",]

[tool.uv.sources]
chatlas-embed = { path = "../chATLAS_Embed", editable = true }
