[project]
name = "amcl"
version = "0.1.2"
description = "AMCL Python Bindings"
readme = "README.md"
requires-python = ">=3.8,<3.14"
authors = [
    { name = "Joshua J. Damanik", email = "joshuajdmk@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/damanikjosh/amcl_python"

[build-system]
requires = ["scikit-build-core >=0.5.0", "nanobind >=1.20.0"]
build-backend = "scikit_build_core.build"


[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "build-system.requires"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Conditionally build stable ABI wheels for CPython 3.12+
# For Python 3.8-3.11: regular wheels, for 3.12+: stable ABI
wheel.py-api = "cp312"
wheel.expand-macos-universal-tags = true

[tool.cibuildwheel]
# Necessary to see build output from the actual compilation
build-verbosity = 1
skip = "pp* *-musllinux_*"
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
archs = ["auto64"]          # Only target 64 bit architectures

# Optional: run pytest to ensure that the package was correctly built
# test-command = "pytest {project}/tests"
# test-requires = "pytest"

# Needed for full C++17 support on macOS
[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "14.0"