[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bbm_q"
version = "0.2.3"
description = "Ultra-minimal."
authors = [{ name = "You", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
dependencies = ["requests>=2.31"]

[project.urls]
Homepage = "https://github.com/yourname/bbm_q"
