[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fast-backend-builder"
version = "0.1.0"
description = "A FastAPI helper/builder package"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name="Japhary Juma", email="japharyjuma@gmail.com" },
  { name="Shija Ntula", email="abuukauthar13@gmail.com" },
  { name="Juma Ludanga", email="ludangajn@gmail.com" },
]
dependencies = [
  "fastapi>=0.100",
  "uvicorn>=0.23"
]
