[project]
name = "galaxy-py-algo"
version = "0.0.1"
authors = [
    { name="Bastien Saltel", email="bastien.saltel@gmail.com" },
]
description = "Python Algorithm for the Galaxy Project"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/bsaltel/galaxy-py-algo"
Issues = "https://github.com/bsaltel/galaxy-py-algo/issues"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
