[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "fun_mathutils_walid"  # unique name on PyPI
version = "0.1.0"
description = "A small math utility module"
authors = [{ name = "Walid Newaz", email = "you@example.com" }]
readme = "README.md"
license = { text = "MIT" }
dependencies = []
[tool.setuptools.packages.find]
where = ["mathutils"]