[tool.poetry]
name = "python-urlopen"
version = "0.1.6.2"
description = "Python urlopen wrapper."
authors = ["ChenyangGao <wosiwujm@gmail.com>"]
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/ChenyangGao/python-modules/tree/main/python-urlopen"
repository = "https://github.com/ChenyangGao/python-modules/tree/main/python-urlopen"
keywords = ["urlopen"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.12"
http_client_request = ">=0.0.7"
http_response = ">=0.0.9"
python-argtools = ">=0.0.2"
python-cookietools = ">=0.1.3"
python-dicttools = ">=0.0.4"
python-filewrap = ">=0.2.8"
python-http_request = ">=0.1.4"
python-undefined = ">=0.0.3"
yarl = "*"

[tool.poetry.scripts]
python-urlopen = "urlopen.__main__:main"
urlopen = "urlopen.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.packages]]
include = "urlopen"
