[project]
name = "amsatop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Oriol Agost Batalla", email = "github@agost.info" }
]
requires-python = ">=3.13"
dependencies = [
    "pyfiglet>=1.0.4",
    "textual>=5.3.0",
]

[project.scripts]
amsatop = "amsatop:main"

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
