[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tg-scrape-comments"
version = "0.1.2.post2"
description = "Telegram channel posts & comments scraper (JSONL per channel)"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Anna Chizhik" }]
keywords = ["telegram", "telethon", "scraper", "comments", "jsonl"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Environment :: Console",
  "Operating System :: OS Independent",
]

dependencies = [
  "telethon>=1.36.0",
  "tqdm>=4.66.0"
]

[project.scripts]
tg-scrape = "tg_scrape_comments.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
