[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "petcmd"
version = "1.0.5"
authors = [{ name = "Maks Vinnytskyi", email = "ownerofforest@gmail.com" }]
description = "Library for creating a command line tools"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://gitlab.com/Tullp/petcmd"

[tool.setuptools]
packages = ["petcmd", "petcmd.autocompletion"]
