[project]
name = "colorby"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = []
authors = [
  { name="Colin Chan", email="colin+colorby@lumeh.org" },
]
description = "CLI for coloring lines from stdin based on a key identified by a regular expression"
readme = "README.md"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Operating System :: POSIX",
  "Programming Language :: Python :: 3",
  "Topic :: Utilities",
]
license = "MIT"
license-files = ["LICENSE"]

[project.scripts]
colorby = "colorby:main"

[project.urls]
Homepage = "https://www.lumeh.org/projects/colorby/"
Issues = "https://github.com/kalgynirae/colorby/issues"

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
