# This section defines the tools needed to build your package.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# This section contains all the metadata for your project.
[project]
name = "KCw-WebSurferAgent"
version = "0.1.1"
authors = [
  { name = "Richter van Emmerik", email = "vanemmerik.richter@kpmg.nl" },
]
description = "This is an agent package to automate KCw workflows."
readme = "README.md"  
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


dependencies = [
    "autogen-ext>=0.7.1",
    "autogen-agentchat>=0.7.1",
    "autogen-core>=0.7.1",
    "azure-core>=1.35.0",
    "azure-identity>=1.23.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "playwright>=1.54.0",
    "azure-ai-inference>=1.0.0b9", 
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
]


[project.urls]
Homepage = "https://github.com/kpmg-nl-emu/dani-agent.git"