[build-system]
requires = [
    "setuptools~=80.9",
    "setuptools-scm~=9.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "pypi-verify-now"
authors = [
    { name = "Joost Molenaar", email = "jjm@j0057.nl" },
]
license = "MIT"
description = "Verifies pypi-attestations in a build pipeline"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
]
keywords = [
    "sigstore",
]
dynamic = [
    "version",
]
dependencies = [
    "pip~=25.2",
    "pypi-attestations~=0.0",
]

[project.scripts]
pypi-verify-now = "pypi_verify_now:main"

[project.urls]
repository = "https://gitlab.com/j0057-git/python/pypi-verify-now"
issues = "https://gitlab.com/j0057-git/python/pypi-verify-now/-/issues"

[dependency-groups]
build = [
    "build~=1.2",
    "pypi-attestations~=0.0",
    "setuptools~=80.9",
    "setuptools-scm~=9.2",
]
publish = [
    "twine~=6.1",
]
dev = [
    {include-group = "build"},
    {include-group = "publish"},
]

[tool.setuptools]
py-modules = ["pypi_verify_now"]
include-package-data = false

[tool.setuptools.package-data]
pypi_verify_now = ["*.md"]

[tool.setuptools_scm]
local_scheme = "no-local-version"
