[project]
name = "mdconv"
version = "0.1.3"
description = "[MDCONV](http://github.com/Juminiy/mdconv) is markdown to [json, ppt, docx, txt] converter"
authors=[
    { name = "Juminiy", email = "chisato-x@bupt.edu.cn" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typing-extensions>=4.15.0",
]

[project.optional-dependencies]
full = [

]

[tool.setuptools]
packages = ['mdconv', 'mdlang', 'pychar']

[tool.ruff]
exclude = [
    ".venv"
]

[project.urls]
Homepage = "https://github.com/Juminiy/mdconv"
Issues = "https://github.com/Juminiy/mdconv/issues"