[project]
name = "mcpccc"
version = "0.2.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "liujingjing", email = "" }
]
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.12.3",
    "requests>=2.31.0",
]

[project.scripts]
mcpccc = "mcpccc:main"

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"
