[project]
name = "wispra"
version = "0.9.1"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "tqdm",
    "scipy",
    "anndata",
    "scikit-learn",
]
authors = [
  { name="Wang Zilu", email="1923524070@qq.com" },
]
description = "A package designed to optimize spatial genomic data processing and downstream analysis of cellular communication."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
"Homepage" = "https://github.com/wangz1lu/wispra"
"Bug Tracker" = "https://github.com/wangz1lu/wispra/issues"
