[package]
name = "Velithon"
version = "0.6.3"
edition = "2024"
description = "Velithon is a lightweight, high-performance, asynchronous web framework for Python, built on top of the RSGI protocol"
authors = ["Dang Van Nghiem <martin@smartsolution.id.vn>"]
license = "BSD-3-Clause"
readme = "README.md"

[lib]
name = "_velithon"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module", "generate-import-lib", "experimental-async"] }
pyo3-async-runtimes = { version = "0.25", features = ["tokio-runtime"] }
regex = "1.10"
uuid = { version = "1.8", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
rand = "0.9.2"
mimalloc = { version = "0.1.47", optional = true }
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.1.2"
crossbeam-channel = "0.5"
parking_lot = "0.12"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1.16", features = ["full"] }
http-body-util = "0.1"
urlencoding = "2.1"
bytes = "1.0"
thiserror = "2.0.12"
ahash = "0.8"
handlebars = "6.2"
percent-encoding = "2.3"
tempfile = "3.8"

[target.'cfg(not(any(target_env = "musl", target_os = "freebsd", target_os = "openbsd", target_os = "windows")))'.dependencies]
tikv-jemallocator = { version = "0.6.0", default-features = false, features = ["disable_initial_exec_tls"] }

[build-dependencies]
pyo3-build-config = "=0.25"

[features]
mimalloc = ["dep:mimalloc"]

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = "debuginfo"
