[build-system]
requires = [ "setuptools", "setuptools-scm",]
build-backend = "setuptools.build_meta"

[project]
name = "ositah"
version = "25.9.dev1"
description = "Outils de Suivi d'Activités basé sur Hito"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "blinker",
    "dash>=2.17",
    "dash-bootstrap-components",
    "flask",
    "flask-multipass",
    "flask-sqlalchemy~=3.0",
    "flask-wtf",
    "hito-tools>=24.8.1",
    "pandas>=2.2",
    "pymysql",
    "python-ldap",
    "pyyaml",
    "simplejson",
    "sqlalchemy~=2.0",
]
dynamic = []
license = "BSD-3-Clause"

[[project.authors]]
name = "Michel Jouvin"
email = "michel.jouvin@ijclab.in2p3.fr"

[project.urls]
Homepage = "https://gitlab.in2p3.fr/hito/ositah"
"Bug Tracker" = "https://gitlab.in2p3.fr/hito/ositah/-/issues"

[project.scripts]
ositah = "ositah.main:main"

[tool.setuptools]
packages = [ "ositah",]
