[project]
name = "ganvil"
version = "1.0.1"
description = "Synchronize and refactor repositories with ease."
authors = [
    {name = "wandhydrant",email = "hydrantanderwand@gmail.com"}
]
license = {text = "MPL-2.0"}
readme = "README.md"
requires-python = ">=3.9"
repository = "https://codeberg.org/ganvil/plugin-python"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Libraries",
]
packages = [
  { include = "ganvil" }
]
dependencies = [
    "grpcio-health-checking (>=1.74.0,<2.0.0)",
    "grpcio (>=1.74.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
# Explicit inlcude prevent Poetry from ignoring the files
# because these are ignored in .gitignore.
include = [
  "ganvil/go_plugin/*_pb2*",
  "ganvil/protocol/v1/*_pb2*"
]

[tool.poetry.group.dev.dependencies]
ruff = "^0.12.10"
pytest = "^8.4.1"
coverage = "^7.10.4"
grpcio-tools = "^1.74.0"

[tool.pytest.ini_options]
addopts = "--ignore integration_test/"

[tool.ruff]
extend-exclude = [
  "ganvil/protocol/v1/*.py", # Auto-generated from protobuf files.
  "ganvil/protocol/v1/*.pyi", # Auto-generated from protobuf files.
  "ganvil/go_plugin/*.py", # Auto-generated from protobuf files.
  "ganvil/go_plugin/*.pyi" # Auto-generated from protobuf files.
]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
