[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "modal-hj3415"
version = "0.1.5"
authors = [{name = "Hyungjin Kim", email = "hj3415@gmail.com"}]
description = "modal-hj3415 is the program for opening the modal window"
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    "django",
    "Pillow",
]

[project.urls]
Home = "https://www.hyungjin.kr"

[tool.flit.sdist]
exclude = ["tests/", ".gitignore"]
