[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lineplot"
version = "0.1.6"
description = "A minimalist line plotting package for live updates from jupyter notebooks."
readme = "README.md"
license = "MIT"
authors = [
  {name = "Benoit Favre", email = "benoit.favre@gmail.com"}
]
requires-python = ">=3.6"
dependencies = ["IPython"]

[project.urls]
"Homepage" = "https://github.com/benob/lineplot"
"Issues" = "https://github.com/benob/lineplot/issues"
