[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "apimatic-twilio-sdk"
description = "Twilio API enables developers to integrate communication services like SMS, voice calls, video, and messaging into applications."
version = "1.0.0"
readme = "README.md"
keywords = []
dependencies = ["apimatic-core~=0.2.0, >= 0.2.20", "apimatic-core-interfaces~=0.1.0, >= 0.1.5", "apimatic-requests-client-adapter~=0.1.0, >= 0.1.6"]
classifiers = []
requires-python = ">=3.7"
[[project.authors]]
name = "Hamza Shahzad"
email = "muhammad.hamza@apimatic.io"

[project.urls]
Documentation = "https://docs.apimatic.io/"
[project.optional-dependencies]
testutils = ["pytest>=7.2.2"]
[tool]
[tool.setuptools]
[tool.setuptools.packages]
[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]
