[project]
name = "sinapsis-huggingface-embeddings"
version = "0.1.8"
description = "Templates to generate and/or extract text and image embeddings using HuggingFace"
authors = [
    {name = "SinapsisAI", email = "dev@sinapsis.tech"},
]
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.2.0",
    "llama-index>=0.12.14",
    "llama-index-embeddings-huggingface>=0.5.1",
    "sinapsis>=0.1.1",
    "soundfile>=0.13.1",
    "speechbrain>=1.0.2",
    "torchaudio>=2.5.1",
    "tree-sitter==0.20.2",
    "tree-sitter-languages>=1.10.2",
]
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
url = "https://pypi.sinapsis.tech/"

[project.urls]
Homepage = "https://sinapsis.tech"
Documentation = "https://docs.sinapsis.tech/docs"
Tutorials = "https://docs.sinapsis.tech/tutorials"
Repository = "https://github.com/Sinapsis-AI/sinapsis-huggingface.git"
