[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ESResolutionScanner"
version = "1.0.2"
authors = [
  { name="Entente", email="your.email@example.com" },
]
description = "A scanner for ES resolutions by country"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.0"
]

[project.urls]
"Homepage" = "https://github.com/yourusername/ESResolutionScanner"
"Bug Tracker" = "https://github.com/yourusername/ESResolutionScanner/issues"