[project]
name = "chattr"
version = "0.0.15"
description = "App part of the Chatacter Backend"
readme = "README.md"
authors = [
    { name = "Mohamed Hisham Abdelzaher", email = "mohamed.hisham.abdelzaher@gmail.com" },
]
requires-python = ">=3.13.7, <3.14"
dependencies = [
    "fastembed>=0.7.2",
    "gradio>=5.43.1",
    "langchain-community>=0.3.28",
    "langchain-mcp-adapters>=0.1.9",
    "langchain-openai>=0.3.31",
    "langgraph>=0.6.6",
    "loguru>=0.7.3",
    "m3u8>=6.0.0",
    "mem0ai>=0.1.116",
]

[project.scripts]
chattr = "chattr.__main__:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest-emoji>=0.2.0",
    "pytest-md>=0.2.0",
    "pytest-mergify>=2025.8.20.1",
    "ruff>=0.12.10",
    "ty>=0.0.1a19",
]
