[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datatrack-core"
version = "1.1.5"
description = "Version Control for Database Schemas"
readme = "pypiREADME.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
  { name = "N R Navaneet", email = "navaneetnr@gmail.com" }
]
dependencies = [
  "typer[all]",
  "PyYAML",
  "sqlalchemy",
  "psycopg2-binary",
  "pymysql",
  "pre-commit",
  "pytest"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Topic :: Database :: Front-Ends",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Utilities"
]

[project.urls]
"Homepage" = "https://github.com/nrnavaneet/datatrack"
"Bug Tracker" = "https://github.com/nrnavaneet/datatrack/issues"

[project.scripts]
datatrack = "datatrack.cli:app"

[tool.setuptools.packages.find]
include = ["datatrack*"]
exclude = ["benchmark_tests*"]

[tool.isort]
profile = "black"
