[workspace]
members = [
    "hessra-token",
    "hessra-config",
    "hessra-api",
    "hessra-sdk",
    "hessra-ffi",
    "hessra-token-identity",
    "hessra-token-authz", "hessra-token-core",
]

exclude = ["hessra-pgrx/hessra_authz", "hessra-py"]

resolver = "2"

[workspace.package]
version = "0.10.1"
edition = "2021"
authors = ["Jake Valentic <jake@hessra.net>"]
description = "Rust SDK for Hessra authentication services"
license = "Apache-2.0"
repository = "https://github.com/hessra/hessra-sdk.rs"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
base64 = "0.22"
biscuit-auth = { version = "6.0.0", features = ["pem"] }
reqwest = { version = "0.12.23", features = ["json", "rustls-tls"], default-features = false }
chrono = "0.4"
dirs = "6.0"
hex = "0.4"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
http = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
