[project]
name = "minesweepervariants"
version = "0.0.0"
description = ""
authors = [
    {name = "WuZh-Rh",email = "you@example.com"},
    {name = "KoolShow",email = "51787949+KoolShow@users.noreply.github.com"}
]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.12,<3.15"

[tool.poetry.dependencies]
ortools = ">=9.13.4784,<9.14.0"
pillow = ">=11.3.0,<11.4.0"
pyyaml = ">=6.0.2,<6.1.0"
flask = { version = ">=3.1.2,<4.0.0", extras = ["async"] }
flask-cors = ">=6.0.1,<7.0.0"
waitress = ">=3.0.2,<3.1.0"
tqdm = ">=4.67.1,<5.0.0"
orjson = ">=3.11.2,<4.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.group.dev.dependencies]
ipython = "^9.4.0"
jurigged = { git = "https://github.com/KoolShow/jurigged.git", rev = "0.6.1-dev" }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
write_to = "minesweepervariants/_version.py"
