[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "basketball-cleaner"
version = "0.1.4"
description = "Fill null basketball stats ratios for your dataset"
requires-python = ">=3.8"
authors = [
    { name="Ananya Srinivas" }
]
license = { text="MIT" }
keywords = ["basketball", "data-cleaning", "sports-analytics"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/yourusername/basketball-cleaner"
