[project]
name = "mcp_rs_publish"
version = "0.1.1"
description = "mcp_rs_publish"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.1",
]
[project.scripts]
mcp_rs_publish = "mcp_rs_publish.command:main"
