[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arcas_parser"
version = "0.1.2"
description = "Analyzer project for Verilog/OpenCores"
authors = [{ name = "Sudheer" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyslang>=8.1.0"
]

[project.scripts]
arcas_parser = "arcas.main:main"

[tool.setuptools]
packages = ["arcas"]

[tool.setuptools.data-files]
"bin" = ["scripts/arcas.sh"]

[tool.setuptools.package-data]
arcas = ["*.py"]
