[project]
name = "whalegamer-forecast-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jker", email = "2933385376@qq.com" }
]
requires-python = ">=3.13.3"
dependencies = [
    "mcp[cli]>=1.13.1",
]

[project.scripts]
whalegamer-forecast-mcp = "whalegamer_forecast_mcp:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
